Dev
Malyby/testNewAngular pull request #1
Opened 2021-12-21 07:38 UTC by Malyby

2021-12-22 11:58 UTC, rumartcer requested changes

2021-12-22 11:58 UTC, rumartcer commented on src/app/component/main-menu/main-menu.component.ts
> +    );
Эта штука нигде не используется

2021-12-22 11:58 UTC, rumartcer commented on src/app/component/modal/add-game/add-game.component.html
> +                Поле платформа обязательна
Текст ошибки не тот

2021-12-22 11:58 UTC, rumartcer commented on src/app/component/modal/add-game/add-game.component.ts
> +  public form: FormGroup|any;
А зачем тут any? Из-за него ломается автодополнение в темплейте, и ошибка появляется вот тут `src/app/component/modal/add-game/add-game.component.html:30`. Вообще лучше без any обходиться, причин уйма. У тебя почему-то на всех формах используется тип `FormGroup|any`, это неправильно. Ты должен понять почему у тебя без any ничего не работает, а не просто костылять any))

2021-12-22 11:58 UTC, rumartcer commented on src/app/component/modal/add-game/add-game.component.ts
> +  platform: string
А зачем тут platform, когда тебе в модалку передаётся player, у которого и так есть platform?

2021-12-22 11:58 UTC, rumartcer commented on src/app/types/game.type.ts
> +    id: string,
А почему у тебя ID игры - это строка? И ты везде кастуешь эту строку к числу при помощи `+game.id`.  Хотя фактически с бэкенда тебе приходит число в качестве ID
![image](https://user-images.githubusercontent.com/22591758/147051372-b4913646-1079-444a-8ee9-117076a61aa1.png)

2021-12-22 11:58 UTC, rumartcer commented on src/app/services/api/game/game.service.ts
> +  public getGameForPlarform = (platform: string): Observable<Game[]> => {
nit
Очепятка в `Platform`, плюс метод лучше назвать `getGamesForPlatform`, потому что у тебя массив игр возвращается, а не одна игра, так очевиднее

2021-12-22 11:58 UTC, rumartcer commented on src/app/component/modal/create-player/create-player.component.scss
> +}
Этот код у тебя дублируется в каждой модалке. Это не очень хорошо, DRY нужно соблюдать, особенно в таком маленьком проекте с кодовой базой на тысячу строк

2021-12-22 11:58 UTC, rumartcer commented on src/app/constans/constans.ts
> +export const platforms = ["PC", "PS", "Xbox", "Nintendo Switch"]
У тебя же ограниченный набор платформ. Почему не сделал enum? И почему во всех местах у тебя platfrom - это string, а platforms - string[]? Если бы ты использовал enum - такого не было бы

2021-12-22 11:58 UTC, rumartcer commented on src/app/component/modal/create-player/create-player.component.ts
> +  public platforms: String[] = [];
Когда используешь примитивы - надо писать их с маленькой буквы, а не классами, это [самая первая рекоментация TS](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#general-types). То есть тут должно быть `public platforms: string[] = [];`

2021-12-22 11:58 UTC, rumartcer commented on src/app/component/modal/create-player/create-player.component.ts
> +  }
Баг: создаю игрока, в списке игроков нажимаю "Показать ещё", и в списке появляется 2 одинаковых игрока
![image](https://user-images.githubusercontent.com/22591758/147066518-cd1d5d68-4831-4e8f-8e5a-707ab38add41.png)

2021-12-22 11:58 UTC, rumartcer commented on src/app/component/modal/create-player/create-player.component.ts
> +      ]),
А почему возраст - необязательное поле? 🤔

2021-12-22 11:58 UTC, rumartcer commented on src/app/component/modal/delete-player/delete-player.component.ts
> +          this.location.back();
nit
Вот из-за этой строчки баг. Если я открываю пользователя в новой вкладке, и удаяю его - всё идёт не так) в таких случаях лучше перенаправлять на определённый роут, в данном случае - на таблицу пользователей

2021-12-22 11:58 UTC, rumartcer commented on src/app/component/modal/delete-player/delete-player.component.html
> +            </span>
Не-не, вот так лучше не делать. Написал тебе почему в самом валидаторе

2021-12-22 11:58 UTC, rumartcer commented on src/app/services/validators/ValidateEqualNickname/validate-equal-nickname.service.ts
> +    }
Кароч вот так лучше не делать. У тебя стандартные валидаторы возвращают в объекте только ошибку, при чём название ошибки совпадает с названием валидатора. Лучше придерживаться этого правила, и вернуть здесь `{equalNickname: true}`, для единообразия API ошибок валидации. Кроме того, хардкодить сюда саму ошибку `Имена не совпадают` тоже не стоит, т.к. в разных местах может понадобиться выводить слегка разные ошибки

2021-12-22 11:58 UTC, rumartcer commented on src/app/services/validators/ValidateUniqueDataPlayer/validate-unique-data-player.service.ts
> +          }),
nit
Лучше следовало вот эту эмуляцию ответа с бэка вынести в отдельный сервис, какой-нибудь типа `EmulateBackendService`, и там уже делать всякие таймеры, поиск по игрокам и т.п. А тут оставить чистый валидатор, как он и должен работать, будто бэкенд реально существует, дабы соблюдать [разделение ответственностей](https://en.wikipedia.org/wiki/Separation_of_concerns)

2021-12-22 11:58 UTC, rumartcer commented on src/app/component/modal/edit-player/edit-player.component.ts
> +  }
Баг: при редактировании игрока я могу убрать ему возраст и сохрать его. В результате у него не будет возраста. То есть будет не 0 лет, а вообще не будет возвраста

2021-12-22 11:58 UTC, rumartcer commented on src/app/component/modal/delete-player/delete-player.component.ts
> +    form.value.age = +form.value.age;
А это тут зачем?

2021-12-22 11:58 UTC, rumartcer commented on src/app/component/modal/edit-player/edit-player.component.ts
> +    }
Баг: игроку 3 года. Я не могу добавить ему игру с рейтингом EC

2021-12-22 11:58 UTC, rumartcer commented on src/app/component/modal/add-game/add-game.component.ts
> +}
Баг: не могу добавить игроку игру, которая вышла сегодня

2021-12-22 11:58 UTC, rumartcer commented on src/app/component/modal/delete-player/delete-player.component.ts
> +  ) {
А почему у тебя все под ряд поля класса публичные? То же самое и с функциями. И так во всех классах

2021-12-22 11:58 UTC, rumartcer commented on src/app/app-routing.module.ts
> +];
Баг: могу пройти по ссылке http://localhost:4200/players/999 и мне не выдастся 404

2021-12-22 11:58 UTC, rumartcer commented on src/app/component/pages/game-list/game-list.component.scss
> +    min-height: calc(100vh - 64px);
А почему по всему проекту раскиданы какие-то хаки с вычислением высоты? В чём была проблема, которую ты решил калком побороть, мне даже интересно

2021-12-22 11:58 UTC, rumartcer commented on src/app/component/pages/not-found/not-found.component.html
> +</div>
Баг: у страницы 404 белый фон, а не тёмный, как у всех остальных

2021-12-22 11:58 UTC, rumartcer commented on src/app/component/pages/not-found/not-found.component.ts
> +  }
Зачем тут `ngOnInit()`?

2021-12-22 11:58 UTC, rumartcer commented on src/app/component/pages/game-list/game-list.component.html
> +    </ng-template>
nit
На всех страницах пока данные не загружены, выводится такая зеродата, мол, данных никаких нет. Но это же не правда, должен быть лоадер, или что-то типа такого

2021-12-22 11:58 UTC, rumartcer commented on src/app/constans/constans.ts
> +}
А почему это константа, а не enum?

2021-12-22 11:58 UTC, rumartcer commented on src/app/services/api/game/game.service.ts
> +  public getPlayerGames = (games_id: number[]): Observable<Game[]> => {
Тут в аргументе должен быть playerId, а не список игр, метод-то называется `getPlayerGames`

2021-12-22 11:58 UTC, rumartcer commented on src/app/services/api/game/game.service.ts
> +  public params: HttpParams = new HttpParams();
Страшнейший баг. У тебя параметры должны каждый раз создаваться новые, внутри каждой функции, а не как сейчас, глобально объявленные. Воспроизвести легко: открой игрока, которому доступна Игра 1, а потом которому доступна Игра 2. Потом снова открой первого игрока, и ты увидишь у него 2 игры вместо одной, потому что у тебя в параметры в методе `getPlayerGames` просто пушатся в параметры ID всех игр подряд

2021-12-22 11:58 UTC, rumartcer commented on src/app/services/api/player/player.service.ts
> +  }
А почему у этой функции отличается от всех остальных возвращаемый результат?

2021-12-22 11:58 UTC, rumartcer commented on src/app/services/api/player/player.service.ts
> +      )
А почему у тебя везде это дублирование кода? Вообще в каждом методе. DRY не соблюдаешь))

2021-12-22 11:58 UTC, rumartcer commented on src/app/services/api/player/player.service.ts
> +      .put<Player>(`${this.API_URL}/players/${player.id}`, player)
Почему тут put, а не patch?

2021-12-22 16:55 UTC, Malyby commented on src/app/component/modal/add-game/add-game.component.ts
> +  public form: FormGroup|any;
Согласен

2021-12-22 16:59 UTC, Malyby commented on src/app/component/modal/add-game/add-game.component.ts
> +  platform: string
Кажется, я тут сам себе напридумывал что-то

2021-12-22 17:01 UTC, Malyby commented on src/app/constans/constans.ts
> +export const platforms = ["PC", "PS", "Xbox", "Nintendo Switch"]
Не знал про enum

2021-12-22 17:02 UTC, Malyby commented on src/app/component/modal/create-player/create-player.component.ts
> +  public platforms: String[] = [];
Да, это я понял в середине написание проекта, и не везде подчистил

2021-12-22 17:03 UTC, Malyby commented on src/app/component/modal/create-player/create-player.component.ts
> +      ]),
без комментариев...

2021-12-22 17:03 UTC, Malyby commented on src/app/component/modal/delete-player/delete-player.component.ts
> +          this.location.back();
Мне тоже такое решение не очень понравилось, но по-другому я не придумал

2021-12-22 17:05 UTC, Malyby commented on src/app/services/validators/ValidateUniqueDataPlayer/validate-unique-data-player.service.ts
> +          }),
Это не таймер для эмулирования запроса, это отбивка, чтобы на каждое нажатие не срабатывал запрос

2021-12-22 17:08 UTC, Malyby commented on src/app/component/modal/edit-player/edit-player.component.ts
> +  }
Да, я понял, это из-за того что я пропустил валидацию на обязательное поле

2021-12-22 17:11 UTC, Malyby commented on src/app/component/modal/delete-player/delete-player.component.ts
> +    form.value.age = +form.value.age;
Здесь этого не должно быть, это делается при создании пользователя

2021-12-22 17:15 UTC, Malyby commented on src/app/component/modal/edit-player/edit-player.component.ts
> +    }
Увидел, сделал строгое сравнение, вместо нестрогого

2021-12-22 17:17 UTC, Malyby commented on src/app/component/modal/add-game/add-game.component.ts
> +}
Кажется тут речь не про сегодня, а про данный момент, я понял, что ты имел ввиду опять строгое сравнение, но сравнение происходит в миллисекундах

2021-12-22 17:19 UTC, Malyby commented on src/app/component/modal/delete-player/delete-player.component.ts
> +  ) {
Я шел по принципу ставлю приватный, если что потом меняю на публичный. И в какой-то момент я перестал так делать и зря. А перестал потому что, если переменная обращается в шаблон, приватной она уже быть не может. Не совсем понял еще, в каких случаях стоит сразу ставить приватный не задумываясь

2021-12-22 17:22 UTC, Malyby commented on src/app/app-routing.module.ts
> +];
Понял, почему так происходит, но пока нет идей как это пофиксить

2021-12-22 17:24 UTC, Malyby commented on src/app/component/pages/game-list/game-list.component.scss
> +    min-height: calc(100vh - 64px);
Если контента мало, то поле не на всю высоту и получается оставался белый кусок, но кажется стоило просто сделать фон у боди серым....

2021-12-22 17:24 UTC, Malyby commented on src/app/component/pages/not-found/not-found.component.ts
> +  }
Даже не залазил в этот файл, автогенерация

2021-12-22 17:25 UTC, Malyby commented on src/app/constans/constans.ts
> +}
Выше отвечал

2021-12-22 17:27 UTC, Malyby commented on src/app/services/api/game/game.service.ts
> +  public getPlayerGames = (games_id: number[]): Observable<Game[]> => {
Не должен) Но я понял к чему ты клонишь, не правильно назвал функцию

2021-12-22 17:31 UTC, Malyby commented on src/app/services/api/game/game.service.ts
> +  public params: HttpParams = new HttpParams();
Понял о чем ты, но почему-то повторить не смог

2021-12-22 17:33 UTC, Malyby commented on src/app/services/api/player/player.service.ts
> +  }
Здесь мне нужно было заглянуть в хедер ответа, чтобы узнать если в поле Link, слово next, чтобы понимать отображать кнопку "Показать еще" или нет. Кажется что это громоздкое и не красивое решение, но другого я придумать не смог

2021-12-22 17:34 UTC, Malyby commented on src/app/services/api/player/player.service.ts
> +      )
Не знал как объединить это все. Хотел как-то обернуть все стримы и один раз обработку ошибки, но мне показалось что сливать все стримы вместе нехорошо

2021-12-22 17:35 UTC, Malyby commented on src/app/services/api/player/player.service.ts
> +      .put<Player>(`${this.API_URL}/players/${player.id}`, player)
Почитал, понял, лучше патч для такой штуки

2021-12-23 08:14 UTC, rumartcer commented on README.md
> +#Тестовое
афы

2021-12-23 08:14 UTC, rumartcer commented on src/app/component/main-menu/main-menu.component.ts
> +    );
123

2021-12-23 08:15 UTC, rumartcer commented on src/app/component/main-menu/main-menu.component.ts
> +    );
321

2022-02-13 16:02 UTC, merged

2022-02-17 05:46 UTC, Malyby commented on src/app/component/modal/create-player/create-player.component.scss
> +}
Не знаю как хорошо это вынести, создал папку styles в корне и там добавил общий файл для модалок